const express = require(`express`)
const app = express()
app.use(express.json())
const userController = require(`../controllers/user.controller`)
app.get("/", userController.getAllUser)
app.post("/login", userController.login)
app.post("/add", userController.addUser)
app.post("/find", userController.findUser)
app.put("/update/:id", userController.updateUser)
app.delete("/delete/:id", userController.deleteUser)
module.exports = app
